### ISSUE TITLE
[FEATURE] Add top-level dev_dependencies field to manifest.json

### ISSUE THREAD

**Issue by halajohn** [TEN-framework/ten-framework#945]
### Description

This field is meant to express dependencies that are only needed in development mode. Note that the name must be exactly `dev_dependencies`.

* **Default mode:** development

  * Running `tman install` (without flags) should install both the `dependencies` and the new `dev_dependencies`.
  
* **Production mode:**

  * Running `tman install --production` should install only the `dependencies` section.

### Required changes

1. **Schema update**

   * In the `manifest.json` JSON Schema, add a new top-level field called `dev_dependencies` with the exact same schema as `dependencies`.

2. **Runtime support**

   * Extend `tman` so it reads and installs packages listed under `dev_dependencies` when in development mode.

3. **Move existing dev-only packages**

   * Move any current dev-only dependencies (e.g. `gtest` ten package, etc.) from `dependencies` into the new `dev_dependencies` field.

### Severity

Major

**Comment by sunxilin** [comment]
# TMan 包管理器中 dev_dependencies 的影响说明

## 概述

在 TMan 包管理器中引入 `dev_dependencies` 后，会对正常的 `tman install` 行为产生以下影响。

## 默认安装行为

执行 `tman install` 时，系统会按照以下规则安装依赖包：

- ✅ 安装 manifest 中声明的 `dependencies`
- ✅ 递归安装 `dependencies` 的依赖包
- ✅ 安装 `dev_dependencies`
- ✅ 递归安装 `dev_dependencies` 的依赖包
- ❌ **不会**安装 `dependencies`/`dev_dependencies` 的 `dev_dependencies`

## 示例说明

假设有以下依赖树结构：

```
dependencies:
  - A
    dependencies:
      - E
        dependencies:
          - M
        dev_dependencies:
          - N          # ← 不会被安装
    dev_dependencies:
      - F              # ← 不会被安装
  - B
    dependencies:
      - G

dev_dependencies:
  - C
    dependencies:
      - I
        dependencies:
          - K
        dev_dependencies:
          - L          # ← 不会被安装
    dev_dependencies:
      - J              # ← 不会被安装
  - D
```

### 默认安装结果

执行 `tman install` 实际会安装：**A, E, M, B, G, C, I, K, D**

### 生产环境安装

执行 `tman install --production` 时，不会安装 `dev_dependencies`，上述示例中会安装：**A, E, M, B, G**

## manifest-lock.json 生成规则

- `manifest-lock.json` 文件的生成**不受** install 时是否指定 `--production` 模式影响
- 始终根据 manifest 中的 `dependencies` 和 `dev_dependencies` 进行计算
- 生成的结果记录默认 `tman install` 会安装的所有依赖包信息

## 总结

这种设计确保了：
1. 开发环境能够获得完整的开发工具支持
2. 生产环境部署时可以排除不必要的开发依赖
3. 锁定文件保持一致性，便于版本管理和协作开发
